### ISSUE TITLE
New pass/receive button for desktop

### ISSUE THREAD

**Issue by blopker** [totem-technologies/totem#152]
@sebasnieb

**Comment by sebasnieb** [comment]
Hi @blopker so for 

Receive 
https://www.figma.com/file/Q8ZcLftDd8JQ9HIFz0DZJD/Totem-app?node-id=1485%3A27185

Pass
https://www.figma.com/file/Q8ZcLftDd8JQ9HIFz0DZJD/Totem-app?node-id=1486%3A27759

**Comment by blopker** [comment]
For simplicity, let's punt on the arrow for now.
