### ISSUE TITLE
Changes for video Self-video

### ISSUE THREAD

**Issue by sebasnieb** [totem-technologies/totem#164]
## Overview
Functionality to allow the user to turn-on and turn off  the self-view when listening to someone.
How this will work is that they will hover over the picture and the Hide Self-view functionality will appear, if activated the video will be blurred out.
To turn on my self-view the user would have to go and hover again over the blurred video and activate it.
## Description
There are only two functionalities that both work while hovering over the picture 
They can be seen here
https://www.figma.com/proto/Q8ZcLftDd8JQ9HIFz0DZJD/Totem-app?page-id=694%3A11492&node-id=1915%3A26673&viewport=241%2C48%2C0.21&scaling=min-zoom&starting-point-node-id=1915%3A26673

@blopker

**Comment by blopker** [comment]
After looking at the mocks, and thinking how it might feel to use, I came up with a potential workflow:

1. Default blurry self-view. It might have the "eye" icon with "Tap to reveal" under it.
2. Person taps/clicks the blurry video and it unblurs, removing the icon and text. Self-view now looks like every other mini portrait view.
3. After 10 seconds, the blur comes back and fades in over a 3 second duration, while also fading in the icon and text. This is so it's not distracting.

The side-effect of this is that we don't need the "Hide self-view" icon and text. Although clicking the unblurred video could still reblur it.

What do you think?

**Comment by sebasnieb** [comment]
Ahh I like that,
How about this somehow:
https://www.figma.com/proto/Q8ZcLftDd8JQ9HIFz0DZJD/Totem-app?page-id=694%3A11492&node-id=1915%3A26673&viewport=-7841%2C-1976%2C0.41&scaling=min-zoom&starting-point-node-id=1915%3A26673&show-proto-sidebar=1

**Comment by sebasnieb** [comment]
This is in a task for the Engineers so I will close it

**Comment by blopker** [comment]
I'm just switching labels. I'll go over this with eng at our next planning session. Thanks!
