### ISSUE TITLE
Delete Account Button

### ISSUE THREAD

**Issue by blopker** [totem-technologies/totem#180]
**Is your feature request related to a problem? Please describe.**
In order to comply with GDPR and just for good privacy practices, we need a "Delete Account" button on the Edit Profile Screen. This needs to include a confirmation modal, so people don't do it on accident.

**Describe the solution you'd like**
Add a "Delete Account" button under the "Sign Out" button on the Edit Profile screen. This needs to include a modal with the text "Are you sure you want to delete all your data? This cannot be undone." With the options "Yes, delete everything" and "Cancel" where "Cancel" is the default option.

**Additional context**
What to delete:

- The account in Firebase Authentication
- Any photos related to the user ID
- Any other personally identifying information: phone number, name, etc

What we don't have to delete: Anything that just lists the user ID. This includes lists of what users were in what circle. This is not PII and is useless to identify the user once the user ID is no longer valid in Firebase Authentication. However, it will help us keep historical records of circle usage.

**Comment by ansells** [comment]
- Implemented custom HTTP function `deleteSelf()` to delete current authenticated user (built-in `auth.deleteUser()` requires re-auth which is problematic with phone auth)
- Installed this plug-in to cleanup ancillary data: https://github.com/firebase/extensions/tree/master/delete-user-data
  - I read through the plug-in code and it looks very well done. 
  - The plug-in triggers off of a user account removal so will work if the account is manually removed
  - The plug-in has flexible configuration options for which collections and storage resources are deleted so it can be updated to include more data if needed without having to deploy new code.
- Implemented unit test for deleteSelf
- Implemented Delete Account button in the profile page with a confirmation dialog
- App calls the `deleteSelf()` firebase function to delete the current user and then logouts of the app if it succeeds

**Comment by blopker** [comment]
Tested! Looks good.
