### ISSUE TITLE
Change size of start circle button

### ISSUE THREAD

**Issue by sebasnieb** [totem-technologies/totem#200]
## Overview
Currently, for the desktop version, we have the start circle button bigger than the rest.
Although this idea was being used at the beginning, it would only work when this button can be in the center, therefore the current amount of actions does not help to highlight the action, and makes it look like a mistake.
To avoid this, let's have it in the same size as the rest 40x40 px size 

## Screenshot

<img width="941" alt="Capture d’écran 2022-06-21 à 5 42 31 PM" src="https://user-images.githubusercontent.com/32967293/174841449-6805861a-d906-45fd-9b2c-87f9c9855ae0.png">

## Description
button resize 40x40 px 
icon size 24x24

FYI @blopker

**Comment by blopker** [comment]
This is for desktop only? Should we normalize it on mobile too?
