### ISSUE TITLE
Change long menu in desktop

### ISSUE THREAD

**Issue by sebasnieb** [totem-technologies/totem#201]
## Overview
Currently on desktop when there is a long menu, the menu is expanding up and down, which in this case do not make a lot of sense since we have the long bar to stack all the buttons.
TO solve this lets leave them across the bar

## Screenshot
<img width="1244" alt="Capture d’écran 2022-06-21 à 9 27 34 PM" src="https://user-images.githubusercontent.com/32967293/174882019-ee5e2020-dd15-4ece-b83a-43f1f2d1536c.png">

## Description
Let's have all the buttons across the bar 
[Figma link](https://www.figma.com/file/Q8ZcLftDd8JQ9HIFz0DZJD/Totem-app?node-id=2522%3A28614)

FYI @blopker

**Comment by blopker** [comment]
Cool, I like that a lot.
