### ISSUE TITLE
New Circle Homepage for browser

### ISSUE THREAD

**Issue by sebasnieb** [totem-technologies/totem#204]
## Overview
Currently, we have for the Circle homepage an adapted version of the app, which is not working completely for browser, therefore let's adapt a more browser-friendly interface.

## Screenshot
<img width="1271" alt="Capture d’écran 2022-06-24 à 4 36 42 PM" src="https://user-images.githubusercontent.com/32967293/175558136-52c191e2-f847-4a9b-a062-433f4546e3f4.png">

## Description
The overall changes are :
Including the logo in the top bar
Having the title bellow (Cricles) 
Moving the button from the lower floating card to be infront (or bellow) the title
Having each section with the appropriate font type (H2)
limiting the size of the circle card to a width of 654px

The breakpoints are 
[Desktop ](https://www.figma.com/file/Q8ZcLftDd8JQ9HIFz0DZJD/Totem-app?node-id=2484%3A28410)
[Tablet landscape](https://www.figma.com/file/Q8ZcLftDd8JQ9HIFz0DZJD/Totem-app?node-id=2566%3A29052)
[Tablet portrait](https://www.figma.com/file/Q8ZcLftDd8JQ9HIFz0DZJD/Totem-app?node-id=2570%3A29130)
[Mobile](https://www.figma.com/file/Q8ZcLftDd8JQ9HIFz0DZJD/Totem-app?node-id=2571%3A29198 )

@blopker FYI

**Comment by blopker** [comment]
Eng note, also look at how the top bar is implemented so that there's no hard yellow cutoff.

**Comment by blopker** [comment]
Eng note, please sort circle by descending creation time (newest at top).
