### ISSUE TITLE
Unstable Network Alert

### ISSUE THREAD

**Issue by sebasnieb** [totem-technologies/totem#208]
## Overview
Alert to let the user know his network signal is unstable

https://www.figma.com/proto/Q8ZcLftDd8JQ9HIFz0DZJD/Totem-app?page-id=694%3A11492&node-id=2595%3A40160&viewport=-118%2C-1050%2C0.17&scaling=min-zoom&starting-point-node-id=1915%3A26673&show-proto-sidebar=1

FYI @blopker

**Comment by blopker** [comment]
Great, do we have the icon assets?
