### ISSUE TITLE
Getting user feedback 

### ISSUE THREAD

**Issue by blopker** [totem-technologies/totem#213]
We need a way for people to provide feedback within the app. Ideally this form will be accessible, but unobtrusive throughout the whole experience. With the submission, we should collect as much data about the current device as needed to diagnose technical issues.

I'm thinking about a small tab at the bottom/side of the screen that people can tap to reveal a text field with a submit button. Submitting the form will thank them and send the data to our database for review.

**Comment by blopker** [comment]
@zevastated

**Comment by micahp2** [comment]
Maybe we can use this link and these questions for getting feedback via Google Docs for now:
https://docs.google.com/forms/d/e/1FAIpQLSf8IuQ6UWEW-9_eX9eSmX5x7Kdabjtg5pmuKQx_4Lc-Amkdmg/viewform?usp=sf_link

**Comment by blopker** [comment]
Cool. The logo is a little large on my screen, but looks good!

**Comment by schalky** [comment]
Added using this button per Micah's input:
![Screen Shot 2022-07-18 at 7 08 21 PM](https://user-images.githubusercontent.com/3159901/179649327-809bc94e-8863-4214-9c0f-4a8f9ac7e2ad.png)

**Comment by blopker** [comment]
Awesome, merged!
