### ISSUE TITLE
Reverse order button

### ISSUE THREAD

**Issue by blopker** [totem-technologies/totem#216]
This ticket is to add a button in the Circle Info modal to reverse the talking order of the circle. This button should take the existing order and reverse it, so the next person is the person who last talked.

If the order is: A>(B)>C>D, and it's currently B's turn, after the button is pressed it should be: C>(B)>A>D

** Assets **
Wireframes and text can be found here: https://drive.google.com/file/d/1z_b7-NkkWBJVfkDWT_eulXYg3KeqkQC-/view?usp=sharing

**Comment by schalky** [comment]
@micahp2 need a button and icon for the button along with where it goes in the UI

**Comment by micahp2** [comment]
Can we use this icon for now? <i class="fa-solid fa-rotate"></i>
Not sure if there's a material or flutter equivalent.
