### ISSUE TITLE
Better handling of baton passing, acceptance, passing, and un-muting

### ISSUE THREAD

**Issue by micahp2** [totem-technologies/totem#223]
As a customer in a circle, I should have a clear and easy way to know when my time to speak is occurring. It is not easy for me to see or understand that I need to activate something so that I can to talk to others in the circle.

To improve this for an MVP release, it is recommended that we do something much more obvious in the UI. This would allow the actions needed by the customer to be obvious and be explained in a way that they can easily take appropriate action. This would also make it more visible as to why they are muted and when they are unmuted.

The current UI seems to be a challenge for the customers I watched using the app in an actual circle session. Each time they were passed the baton they just started speaking, but they were muted, and they did not know how to accept the baton or pass it without multiple live prompts from the keepers.

A wireframe example of how we might approach an MVP solution will be attached to this ticket shortly.

**Comment by micahp2** [comment]
I have some examples of what a floating prompt to help with these issues might look like, saved here:
https://drive.google.com/file/d/1hDrL1DFNI8a70aiGVgHkaPdD066fqpNI/view?usp=sharing

**Comment by blopker** [comment]
Nice! This will definitely help people understand what is going on. When we
spoke, I imagined it more full screen or larger. Is that out of scope for
the mock, or did I visualize it wrong?

For the settings button, are we going to also add it somewhere else in the
UI? Maybe this modal is good enough.

For the pass button, I like the idea of having one CTA on that modal and
people can just pass once it's closed, like a normal turn. Thoughts?

**Comment by blopker** [comment]
Sounds good! Thanks for clarifying.

**Comment by micahp2** [comment]
After some further discussion with @schalky I've taken another pass at this: 
https://drive.google.com/file/d/1hDrL1DFNI8a70aiGVgHkaPdD066fqpNI/view?usp=sharing

Now there is a nearly-full-screen takeover shown to the next participant that is selected to share. There are some helpful prompts shown in that takeover to help them decide what to do next.

While they are in that prompt view, everyone else in the session sees a waiting screen (slide 2). This will help prevent the awkward throwing of the selected share-person's face up in front of everyone while they decide what to say or whether to accept the share request.

@blopker this is closer to what we originally discussed, I think. I still think that some version of slide 1 needs to be presented to the upcoming share-person before they are pushed on stage, but this might be a half-measure to see if it makes the process any easier. 

Feedback welcomed.

**Comment by blopker** [comment]
Notes: Revert video quality settings and move to new branch. We can check it out later.
