### ISSUE TITLE
Account States

### ISSUE THREAD

**Issue by micahp2** [totem-technologies/totem#226]
As a system administrator I need a way to set different account states so that customers go through the correct user experiences and see the correct prompts at the right times based on meeting certain conditions.

A flexible means of creating and managing states is requested. What that could look or act like would be:
- A brand new Customer who hasn't completed all needed fields in the on-boarding flow would be set to an "Invalid Account" state, so that the system would nudge them back into a flow to complete those fields
- A new Customer who hasn't seen the first-run experience would have a not-completed "First-Run" state, so the system would show them the first-run experience at the earliest possible time
- All customers who login after the platform posts new Terms of Service would have a not-completed "2022-Terms_of_Service" state, so the system would make sure they see and accept the new TOS at the next login
- etc.

These states should be applied and managed independently of the Permission levels. That way they could be assigned (or not) to each level by an Administrator based on whether or not they are needed, rather than some hard-coded rule set.

The states should be checked each time the customer logs in. If any of these states are incomplete the rest of the Totem experience should be blocked and the customer should be taken to the appropriate view or flow needed to complete the missing state. 

The customer should never be able to join a session until these required states are completed.

To get started, lets define the following states to use for now:

1. Signup_Incomplete - one or more required fields in the customer's profile are empty; this is only cleared once the customer has fully filled out the fields AND verified the required ID method(s) (entering correct codes from either email or a mobile number)
2. First_Run_Incomplete - the first run experience has either not been completed or the customer has not explicitly skipped the experience; only cleared once the customer has interacted with the first run experience and completed it or skipped it
3. TOS_Not_Accepted - the Totem Terms of Service have not been viewed or accepted; this clears only after the customer has accepted the TOS

**Comment by blopker** [comment]
This library has a cool feature that may solve this: https://pub.dev/packages/auto_route#route-guards Maybe our own version of that could be used.

@schalky, happy to brainstorm this when you're ready.

**Comment by micahp2** [comment]
I've updated the requirements to put in what I think the MVP set will be. We can talk more about it once you all have time to review it: @blopker and @schalky

**Comment by blopker** [comment]
To capture what @schalky an I discussed about implementation:

- Use a 'guard' array that contains functions or classes that take in account data and returns a String?
- For each guard, evaluate it and redirect to the first non-null String returned.
- This should happen only for logged in users, and before any dynamic links.
- If a redirect needs to happen, safe the location they were going and restore that state after the guard is complete.
- We could only do this check on the home screen, as long as it's done before dynamic links, and it's reasonably fast.
- Ideally, we'd make no async calls in these checks as all data we need will have be loaded on initialization.

**Comment by blopker** [comment]
Merged!
