### ISSUE TITLE
Modal window on Circle login/start is getting cut off at the bottom

### ISSUE THREAD

**Issue by micahp2** [totem-technologies/totem#227]
On some people's browser windows, the bottom rounded parts of the UI get cut off or obscured below the bottom of the visible canvas space. 

**Steps To Reproduce**
1. Go to the app page/website
2. Login as any user
3. Wait for the UI to load
4. Join a Circle
5. Scale the browser window until the Join UI is larger that the available canvas
6. Notice that the UI does not resize
7. Notice that the UI does not let the user scroll down to see the rest of the cut off UI

**Expected behavior**
The entire UI should be available see by some means or method and not be cut off and hidden. 
Scrolling down to see it could be acceptable
Scaling the UI down enough to fit within the available canvas could be acceptable

**Screenshots**
Screenshot of this behavior is attached.

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro 64-bit
 - Browser Chrome 64-bit
 - Version 103.0.5060.114
 - Browser Edge 64-bit
 - Version 103.0.1264.62 
<img width="819" alt="chrome-cut" src="https://user-images.githubusercontent.com/3095168/179871140-66f5b6a6-d6b1-4bc2-aed1-935872625f68.png">
<img width="960" alt="Edge-cut" src="https://user-images.githubusercontent.com/3095168/179871141-8b74c9b8-ab38-47d9-aad1-c9cad6d5e2fb.png">

**Comment by schalky** [comment]
kyle working on this one.

**Comment by micahp2** [comment]
Issues found in this fix:

1. On a "clean" or "cold" start of the app, the selected camera device does not match the active camera. See image attached for example
2. When the window is scaled down, text is cut off on the multi-select buttons. See image attached for example
3. When the window is really scaled down, the elements in the window don't scale or flow to make use of available space, leading needed controls to be cut off from the UI. Alternatively, no warning message is shown asking for more window size to show all the needed controls



![Image](https://user-images.githubusercontent.com/3095168/182729341-e2fd7f07-7529-4d20-a62b-1a5d163f9353.png)
![Image](https://user-images.githubusercontent.com/3095168/182729342-b0f61585-a0f6-4d1f-8485-724622b0fa00.png)
![Image](https://user-images.githubusercontent.com/3095168/182729343-91bc81bd-89fb-4a77-af74-0cb1436310b9.png)

**Comment by p2-kyle** [comment]
#1 and #3 will be addressed as separate issues.
#2 has been added as part of the fix.
