### ISSUE TITLE
Convert all icons to use material icons instead of SVGs

### ISSUE THREAD

**Issue by schalky** [totem-technologies/totem#237]

**Comment by micahp2** [comment]
Icon swaps here:
mute material icon named "mic off"
unmute material icon named "mic"

stop video material icon named "videocam off"
show video material icon named "videocam"

Settings material icon named "settings"

Exit / Close material icon named "close"

Info material icon named "info outline"

More material icon named "menu"

Next material icon named "fast forward"

End Circle material icon named "cancel"
