### ISSUE TITLE
Keeper Mute All But Receiver

### ISSUE THREAD

**Issue by micahp2** [totem-technologies/totem#239]
Provide a button based method for the Keeper, while in a circle session, to switch all other participants EXCEPT the person with the totem/baton into a mute state.

** Assets **
Wireframes, layout, and text can be found here: https://drive.google.com/file/d/1z_b7-NkkWBJVfkDWT_eulXYg3KeqkQC-/view?usp=sharing

Use this icon: fa fa-group

**Comment by blopker** [comment]
I've needed this in the past!

**Comment by schalky** [comment]
@micahp2  Need design/icon/placement for the button

**Comment by micahp2** [comment]
Can we try this icon for now?  <i class="fa-solid fa-users-slash"></i>
