### ISSUE TITLE
MVP Account Setup Fields

### ISSUE THREAD

**Issue by micahp2** [totem-technologies/totem#244]
For all new accounts being created, these are the required MVP fields that need to be enforced as part of the setup flow:

- Name (single text field, up to 50 alpha chars, no validation)
- Email (single text field, up to 50 alpha chars, validated X@Y.Z pattern)
- Mobile phone (single number field, up to 15 chars, validated as phone pattern)
- Age of consent acceptance (integer, boolean; whatever works to know the answer is either "has accepted" and "has not accepted")
- Terms of Service acceptance (integer, boolean; whatever works to know the answer is either "has accepted" and "has not accepted")
- Privacy Policy acceptance (integer, boolean; whatever works to know the answer is either "has accepted" and "has not accepted")
 
Mock up wireframe with all language text is here: https://drive.google.com/file/d/1q9dFhuvLsTPePLww_q3vn0AxU7_TkCQQ/view?usp=sharing

Privacy policy link: https://www.heytotem.com/privacy-policy
Terms of Service link: https://www.heytotem.com/tos

**Comment by micahp2** [comment]
@blopker from our last conversation I believe this is our minimum set, but please confirm.

**Comment by blopker** [comment]
Looks good! I think even the email could be optional, unless we really care about validating the wait-list.

**Comment by schalky** [comment]
@micahp2 need details for text and links and design
