### ISSUE TITLE
Donation Link

### ISSUE THREAD

**Issue by micahp2** [totem-technologies/totem#258]
We need a way to show a "Donate" or donation link to each Circle session experience. This will allow customers to pay for a session or send money to the platform and Keeper.

@blopker has a Stripe account already set up, so we can get the API keys and details from him. 
I believe that we'll need a way to track and report the following platform information along with the Stripe integration:

- Keeper name
- Keeper ID
- Keeper Tax information (TBD on this)
- Circle name
- Circle ID

This Donate link would need to be present in the following places:

- On the Home screen (as part of a general "send money to this project" CTA)

In the future we would look to integrate in these additional locations:
- On the Circle join and profile pages
- On the Keeper profile pages
- Within the customer experience, near the other functional buttons (e.g. Mute, Hide, Settings, etc)

URL for the Donate link: https://donate.stripe.com/28obM32nf6TF7n2001

Possible icon: class="fa-solid fa-circle-dollar-to-slot"

Wireframes: https://drive.google.com/file/d/1xaHdQiSAilFuVVqAOv2vhlbj2tGnvWdj/view?usp=sharing

**Comment by blopker** [comment]
Maybe as a first cut we can just have a donate button on the home screen? This would mean recording that metadata could be done in a second chunk. I also don't know if we want the donate button in the core experience itself, or only after the session has ended? I wouldn't want someone to hit it on accident and be taken out of the experience. 

We'll also want one on the marketing site, but perhaps that's a different mechanism.

**Comment by micahp2** [comment]
I would assume that the marketing site would use something embedded, like this perhaps?
https://checkout.stripe.dev/

**Comment by blopker** [comment]
Yeah, that's nice. Thanks.

**Comment by schalky** [comment]
@micahp2 please add design to the end screen for where the button goes and how it looks

**Comment by micahp2** [comment]
Wireframes, icons, and links are all updated at the top of the ticket.
