### ISSUE TITLE
Keeper roles and features for new Permissions

### ISSUE THREAD

**Issue by micahp2** [totem-technologies/totem#265]
Set the specific roles and capabilities for each user type:
* Keepers can create Circles
* Some Admins may create Circles (one-off permission per Admin account)
* Keepers can kick/ban customers
* Admins can kick/ban customers

**Comment by ansells** [comment]
For creating circles, I would presume giving those users the "keeper" and "admin" roles would suffice.
For the kick/ban permission, I would assume that "keepers" can only do so for circles they create, but "admins" can do so for any circle.
Do these sound right?

**Comment by micahp2** [comment]
For whatever reason my comments didn't seem to make it here. Yes, those permissions sound fine
