### ISSUE TITLE
Add images to Circle creation and edit flows

### ISSUE THREAD

**Issue by micahp2** [totem-technologies/totem#283]
As a keeper, I need a way to add images to my circle sessions, so that people can easily identify and find my sessions.

**What Image Sizes**
We need to support at least two different sizes:
- a 1000x300 pixel (width x height) banner-style image
- a 300x300 pixel "circle highlight" image
- Web and mobile standard image formats should be supported: PNG, JPG, WEBP, HEIC, BMP
- any bit depth up to 32-bit should be supported
- transparency or matte channels should be supported
- should support two different image files for the two sizes

**What Image Size Shows Up Where**
- the 1000x300 appears only on the Circle or session profile page
- the 300x300 appears on the home screen (for the sessions being shown), or anywhere else in the UI where a summary or short list of circle sessions appear

**What to do if there are no Images provided**
- the system should programmatically generate placeholder images for the Keeper if they choose not to provide one
- these generated images could be something as simple as a random color and text overlay from the session title

**Where this setting appears**
- Whenever a circle or session is created
- Wherever a circle or session can be edited

**Who can change this setting**
- The Keeper who creates the circle or session
- Admins

**Comment by micahp2** [comment]
@schalky the placeholder images can be found here:
https://drive.google.com/drive/folders/1nDwX7lDWG8j1gsJQGtINW8YzAVT6K9gN?usp=sharing

**Comment by schalky** [comment]
implemented with placeholder images
