### ISSUE TITLE
Add attendee limit to Circle creation and edit flows

### ISSUE THREAD

**Issue by micahp2** [totem-technologies/totem#305]
Allow the Keeper to set the number of attendees available to join a session.
This number can be set at creation time, or at any future edit time.
Preset options go from 2 to 20. Allow the person editing to override this number to any number they wish.
Default for Keepers is 20
Default for non-Keepers is 5
For non-Keepers, we will restrict the total number to 5, which cannot be overridden with more attendees. If they want to set it to less than 5, that is fine.

**Comment by blopker** [comment]
A 20 default for Keepers might be nice, less for non-Keepers.
