### ISSUE TITLE
Investigate scheduling and calendaring

### ISSUE THREAD

**Issue by micahp2** [totem-technologies/totem#307]
Do some work to find out what would be required to provide the following features in the product:

- Create future sessions that start at a particular date and time
- Create repeating sessions that have variable time durations between occurrences
- Create repeating sessions that end at a specific date, or after a set number of occurrences
- Create calendar invites in these formats: Google Calendar, Apple Calendar, Microsoft Outlook, iCal generic
- Support updating calendar invites after a session is edited or changed
- Clean up of any invites or sessions if they are cancelled or they complete

**Comment by ansells** [comment]
@micahp2 A few comments on this ticket:
"repeating sessions that have variable time durations between occurrences"
Does this just mean Every X days/weeks/months etc? Or do you actually mean that the time durations between each could change? (i.e. Tu of this week, Wed of the following then Mon then Thu....) Hopefully the former as the latter would be challenging to say the least. At any rate, we should decide what sort of repeats we are going to support and define them.

"calendar invites in these formats":
FYI, Apple, Outlook and iCal (or whatever local program you have configured) all pretty much use iCal. Outlook can use an older spec (xCal I think?) if you want to support very old versions. Only Google calendar is really a different format/API

"updating calendar invites after a session is edited or changed":
Importing events into a user's calendar always has to be done via an explicit user action so this cannot be done automatically. I believe it is possible to update a previously imported event by using a well-defined event identifier, but I also know there are some "gotchas" here.

"Clean up of any invites or sessions if they are cancelled or they complete":
Not sure this is really possible in terms of exported events into a user's external calendar program.

**Comment by micahp2** [comment]
@ansells here are some answers (hopefully):

**Repeating session with variable time durations** means, for this feature, that we could support "a session on the second Tuesday of the month" or "every 15 days, except weekends" kind of variability 

**Calendar invites** I think it's just iCal and Google's unique format, though I couldn't find the Apple specific docs to be sure for iOS

**Updating invites after edits** just means we need a way for people to be informed that dates/times changed. This is a challenge currently in that Keepers have to do a lot of manual re-creation of invites to get the word out

**Clean up of cancelled or complete invites** is mainly for the Totem system, although I thought I've seen such a cancellation ICS notice sent out to me on some occasions that did clean out multiple meetings in the same series that were stopped.
