### ISSUE TITLE
Bug: everyone should be put on mute as soon as the Keeper selects End Circle

### ISSUE THREAD

**Issue by micahp2** [totem-technologies/totem#329]
Currently, when a keeper chooses to end the current session, for some period of time afterward all participants can continue to talk and be heard among each other if they were unmuted at the time the session was ended. This behavior is not correct.

Instead, the moment that the Keeper chooses "End Circle" then all participants, including the keeper, should be muted OR the audio and video streams should be stopped such that no one can hear or communicate with each other.

If the keeper backs out and does not fully end the circle, then the connections could be restored or the person with the totem could be unmuted. However, everyone else should remain muted.

**Comment by blopker** [comment]
Can we add to this that starting the circle should mute everyone too? There's about 5 second between the waiting room and circle view that people can't see each other, but can still talk. It feels like a bug right now.

**Comment by micahp2** [comment]
Captured this start circle issue here: https://github.com/totem-technologies/totem/issues/333
