### ISSUE TITLE
Fix: always make Keeper the first participant to share in a Circle session

### ISSUE THREAD

**Issue by micahp2** [totem-technologies/totem#365]
To help Keepers better manage their circle sessions, a request has been raised to make sure that the Keeper is always the person that gets chosen first to share when a session starts.

Presently, when the session begins a customer may be chosen to go first. This makes it awkward for the Keeper as they must scramble to edit the order of participants or manually jump in and talk over others.

Instead, we should set a rule that Keepers who create or run a session (also applies to members who create their instant sessions) should become the first person in the queue and therefore are the first person to appear on stage and speaking after starting a session.

**Comment by micahp2** [comment]
@schalky , @blopker had asked me if we could make a change to this fix to work this way:

- if there has been no participant "order editing" during the time spent in the waiting room, then make the Keeper go first
- if "order editing" in the waiting room has happened, then leave that order alone and don't make the Keeper first

Is that possible?

**Comment by schalky** [comment]
i handled this in the implementation (this = no reset if manually reordered)
