### ISSUE TITLE
Bug: Receive button appears above your self video

### ISSUE THREAD

**Issue by micahp2** [totem-technologies/totem#407]
After a failure in a running session, I rejoined an in-progress session with only myself in it. Upon joining I see this screen (below) where the button to "Receive" is above my self video. This should be the other way around, where the button is below the video.

This is the second time I've seen this issue, but its the first time I have captured it.

![Image](https://user-images.githubusercontent.com/3095168/202312351-51ffe446-9382-4ff0-88a9-40bf02973405.png)

**Comment by blopker** [comment]
Done!
