### ISSUE TITLE
Keepers should be able to remove people from groups

### ISSUE THREAD

**Issue by blopker** [totem-technologies/totem#62]
While in circle, keepers will be able to use the profile modal to remove people from the group (with a confirm dialogue).

When a Keeper clicks a person's profile image, the profile modal should come up as usual. However, only the Keeper will see an option to Remove From Circle.

<img width="412" alt="image" src="https://user-images.githubusercontent.com/757503/150416295-6c182d19-3af3-41ae-a645-e7090de646bb.png">

**Comment by schalky** [comment]
What is the messaging/experience for the user that has been removed?

**Comment by blopker** [comment]
Good question. Let's do something simple for now. Once they get removed, drop them on the home screen with a dialog box saying "You have been removed from the circle." and "OK" as the dismiss button.

**Comment by blopker** [comment]
Also, remove that person from the circle list, so they don't get a "Circles Completed" count. Add them to a "Removed list" so they can't come back to the same circle while it's in pre circle.

**Comment by micahp2** [comment]
For customers removed from a circle:
- if this happens during a live circle session, they are booted to a dead-end page immediately 
- the dead-end page should not allow them to rejoin the circle from which they were just removed
- a feedback button should be provided on the dead-end page
- they should see a message making it clear that they were booted, e.g. "You have been removed from this Circle: <name of circle>"
- they will not have their personal stats updated to reflect that they completed this circle session
- if they wanted to rejoin the circle, they would need to go find the circle profile page and apply to join the circle once again. there would be no means for them to rejoin via any of their existing UI paths that list or show the circle from where they were removed
